### ISSUE TITLE
Eliminar modo debug de la web

### ISSUE THREAD

**Issue by neokore** [svqtech/web#1]
![image](https://user-images.githubusercontent.com/938057/76449394-4c220e80-63cc-11ea-8130-17712590d6e1.png)

**Comment by mpc** [comment]
Done

**Comment by neokore** [comment]
Wow, that was fast!

**Comment by neokore** [comment]
Not yet, it is still there. Checking diff file you modified the generated assests, not the ones from source.

**Comment by neokore** [comment]
Now it is! 😉
