### ISSUE TITLE
Ancho de las páginas

### ISSUE THREAD

**Issue by Delawen** [svqtech/web#10]
¿Se podría ampliar el ancho de https://svqtech.com/evento/ ?

Ahora mismo es una columna un poco estrecha, ¿no?

**Comment by mpc** [comment]
Estaba buscando una imagen del estilo de las otras para esa página, por eso estaba sin nada. Ya he puesto una. De todas formas, la plantilla general se puede modificar sí lo ves demasiado raro.

**Comment by lamujeresponja** [comment]
La imagen sale abajo del todo. Mejor si se pudiera mostrar arriba sobre todo en paginas con mucho texto.

**Comment by mpc** [comment]
Es una decisión de diseño del tema. En móvil sí sale arriba. A mi sí me hace gracia pero lo veis claro lo cambiamos.

**Comment by mpc** [comment]
Hecho
