### ISSUE TITLE
Página de contacto

### ISSUE THREAD

**Issue by Delawen** [svqtech/web#4]
Crearla y enlazarla a un correo, borrarla o poner lo que sea, pero que no dé 404.

Le paso la pelota a @israbr que es el que tiene el dominio y nosequé automático del flusiflús.

**Comment by Delawen** [comment]
@javivigu entiendo por lo que pones en el chat que:

IMPORTANTE: La gestión del buzón contacto@svqtech.com.

**Comment by israbr** [comment]
Creadas:
contacto@svqtech.es
hola@svqtech.com

@javivigu tiene crendeciales para ambas
